name: Build project
 
on:
  push: 
    branches:
      - main
  workflow_dispatch:  
jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps: 
    - name: buildstep1
      uses: actions/checkout@v4

jobs:
  example:
    runs-on: ubuntu-latest # All OS are supported!
    steps:
    - uses: actions/checkout@main        # replace @main with desired version
    - uses: fleshgrinder/setup-java@main # replace @main with desired version
    - run: java -version                 # 🎉  
